[build]
  # Build command - none needed for static site
  command = "echo 'Static site - no build required'"
  
  # Publish directory - current directory contains all files
  publish = "."

[build.environment]
  # Node version for any build processes
  NODE_VERSION = "18"

# Redirect rules for single page application behavior
[[redirects]]
  from = "/learn/*"
  to = "/learn.html"
  status = 200

[[redirects]]
  from = "/course/*"
  to = "/learn.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://apis.google.com https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://identitytoolkit.googleapis.com; img-src 'self' data: https:; frame-src https://accounts.google.com;"

# Performance optimizations
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Error pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Functions (if needed later)
[functions]
  directory = "netlify/functions"